# Generated by Django 5.0.6 on 2024-05-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.TextField(verbose_name='Номер')),
                ('name1', models.TextField(verbose_name='Имя1')),
                ('about1', models.TextField(verbose_name='Болезнь1')),
                ('temp1', models.TextField(verbose_name='Температура1')),
                ('date1', models.DateField(verbose_name='Дата поступления1')),
                ('name2', models.TextField(verbose_name='Имя2')),
                ('about2', models.TextField(verbose_name='Болезнь2')),
                ('temp2', models.TextField(verbose_name='Температура2')),
                ('date2', models.DateField(verbose_name='Дата поступления2')),
                ('name3', models.TextField(verbose_name='Имя3')),
                ('about3', models.TextField(verbose_name='Болезнь3')),
                ('temp3', models.TextField(verbose_name='Температура3')),
                ('date3', models.DateField(verbose_name='Дата поступления3')),
                ('name4', models.TextField(verbose_name='Имя4')),
                ('about4', models.TextField(verbose_name='Болезнь4')),
                ('temp4', models.TextField(verbose_name='Температура4')),
                ('date4', models.DateField(verbose_name='Дата поступления4')),
            ],
            options={
                'verbose_name': 'Палата',
                'verbose_name_plural': 'Палаты',
            },
        ),
    ]
